apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pulsar
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://pulsar.apache.org/charts
    chart: pulsar
    targetRevision: 4.2.0
    helm:
      values: ""
  destination:
    server: https://kubernetes.default.svc
    namespace: storage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
