apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-ui
  namespace: argocd
  labels:
    app: kafka
spec:
  project: default
  source:
    repoURL: https://kafbat.github.io/helm-charts
    chart: kafka-ui
    targetRevision: 1.6.4
    helm:
      values: |
        service:
          type: NodePort
        yamlApplicationConfig:
          kafka:
            clusters:
              - name: yaml
                bootstrapServers: kafka-cluster-kafka-bootstrap.kafka.svc:9092
          auth:
            type: disabled
          management:
            health:
              ldap:
                enabled: false
  destination:
    server: https://192.168.48.191
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
