resources:
  - ../../apps/kafka
  - ../../apps/prometheus
  - ../../apps/chaos
  - ../../apps/load/kafka

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
    patch: |
      - op: replace
        path: /spec/destination/server
        value: "https://192.168.48.193"
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
    patch: |
      - op: replace
        path: /spec/source/repoURL
        value: "https://github.com/P-e-t-e-r-s-e-n/Bachelor"

namePrefix: stu245087-