apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: flink-kubernetes-operator
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - flink
  selector:
    matchLabels:
      app: flink-session
  podMetricsEndpoints:
    - port: metrics
      interval: 5s